PATH_TO_ISAACGYM=
PATH_TO_MUJOCO210=
PATH_TO_ENVIRONMENT=
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PATH_TO_ISAACGYM/python/isaacgym/_bindings/linux-x86_64:$PATH_TO_MUJOCO210/bin:$PATH_TO_ENVIRONMENT/lib
export MUJOCO_PY_MUJOCO_PATH=$PATH_TO_MUJOCO210
